[package]
name = "life_ggez"
version = "0.1.0"
authors = ["samael"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.0"
rand = "0.8.4"